import * as fs from "fs/promises";
import * as zlib from "zlib";
import { promisify } from "util";
import { NativeImage } from "../src/native-image";
import { Canvas } from "../src/canvas";
import { calculateDimensionPx, calculateRequiredPxPerCu, encodeCardData } from "../src/encoding";
import sharp from "sharp";
import { unpackColor } from "../src/color";

const brotliCompress = promisify(zlib.brotliCompress);

async function imageToPng(image: NativeImage): Promise<Buffer> {
  const raw = new Uint8Array(image.asUint32Array().buffer, image.asUint32Array().byteOffset, image.asUint32Array().byteLength);
  return sharp(raw, {
    raw: { width: image.width, height: image.height, channels: 4 }
  }).png().toBuffer();
}

async function pngToImage(buffer: Buffer): Promise<NativeImage> {
  const { data, info } = await sharp(buffer).raw().toBuffer({ resolveWithObject: true });
  const image = await NativeImage.create(info.width, info.height);
  new Uint8Array(image.asUint32Array().buffer, image.asUint32Array().byteOffset, image.asUint32Array().byteLength).set(data);
  return image;
}

const text = await fs.readFile("demo/prefab.vgp", "utf-8");
const compressed = await brotliCompress(Buffer.from(text, "utf-8"));
const base64 = compressed.toString("base64");
const payload = "pa_prefab_br1:" + base64;
const data = new TextEncoder().encode(payload);

const pxPerCu = await calculateRequiredPxPerCu(data.length);

const imageDimension = await calculateDimensionPx(pxPerCu);
const image = await NativeImage.create(imageDimension, imageDimension);
image.asUint32Array().fill(0xFFFFFFFF); // white background

await encodeCardData(image, pxPerCu, data);

let canvas = await Canvas.create(image);
canvas.fillRect(14, 14, 228, 26, unpackColor(0xFF000000));
canvas.fillRect(14, 42, 100, 100, unpackColor(0xFF000000));
canvas.fillRect(14, 144, 228, 98, unpackColor(0xFF000000));
canvas.drawTextCenterAligned(128, 19, 3, "TOOL PREFAB", unpackColor(0xFFFFFFFF));
canvas.drawTextCenterAligned(177, 42, 2, "CHARACTER", unpackColor(0xFF000000));
canvas.drawText(120, 56, 2, "FRAMES", unpackColor(0xFF000000));
canvas.drawTextRightAligned(236, 56, 2, "50", unpackColor(0xFF000000));
canvas.drawText(120, 69, 2, "LENGTH", unpackColor(0xFF000000));
canvas.drawTextRightAligned(236, 69, 2, "5S", unpackColor(0xFF000000));
canvas.drawText(120, 82, 2, "FPS", unpackColor(0xFF000000));
canvas.drawTextRightAligned(236, 82, 2, "10", unpackColor(0xFF000000));
canvas.drawTextCenterAligned(128, 147, 2, "RALSEI SPIN", unpackColor(0xFFFFFFFF));
canvas.drawText(17, 161, 2, "RALSEI SPINNING! :D", unpackColor(0xFFFFFFFF));
canvas.drawText(17, 234, 1, "SPARITE.REIMNOP.COM", unpackColor(0xFFFFFFFF));
canvas.drawTextRightAligned(239, 234, 1, "GENERATED BY CARDCANVAS.JS", unpackColor(0xFFFFFFFF));

const thumbnailBuffer = await fs.readFile("demo/thumbnail.png");
const thumbnail = await pngToImage(thumbnailBuffer);
var thumbnailX = 16 * pxPerCu + (48 * pxPerCu - thumbnail.width / 2);
var thumbnailY = 44 * pxPerCu + (48 * pxPerCu - thumbnail.height / 2);
canvas.drawSubImage(thumbnailX, thumbnailY, thumbnail);

await fs.writeFile("demo/output.png", await imageToPng(image));

console.log(`done, pxPerCu=${pxPerCu}, dimension=${image.width}px`);